In [7]:
import requests

# URL of the dataset
url = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"

# Fetch the data
response = requests.get(url)

# Save the file
with open('input.txt', 'wb') as f:
    f.write(response.content)

# Now, read the file
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# Print the first 500 characters to check
print(text[:1000])


First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [8]:
#Here are all the unique characters that occurs in this text

chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [12]:
#Tokenzie the input text , in simple we are going to convert the unique character we got into in the list and then convert them into numbers
stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars)}
print(stoi)
print(itos)
encode = lambda s: [stoi[c] for c in s] #encoder : take a string, output a list of integers
decode= lambda l: ''.join([itos[i] for i in l])

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}
{0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i',

In [13]:
print(encode("hi there"))


[46, 47, 1, 58, 46, 43, 56, 43]


In [14]:
print(decode([46, 47, 1, 58, 46, 43, 56, 43]))

hi there


In [ ]:
import torch #using pytorch
data = torch.tensor(encode(text),dtype=torch.long)
print(data.shape,data.dtype)
print(data[:1000])
#the way the first 1000 character looks like this to the chatgpt

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [ ]:
n = int(0.9 * len(data))
train_data = data[:n]
val_data =  data[n:]
# we are splitting the data into train and validation data 90 percent of the data goes into the train_data

In [ ]:
block_size = 8 # we use characters of this block size and then train the model as these
#block sizes wont be computallionally not heavy and the we randomly use these block_size from
#the middle of the data
train_data[:block_size+1]
#These are the first 9 characters in the train_data
#

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [ ]:
#lets see what are we doing here
#say 18 is the first number the next number or the next character can be 47
# when we have 18,47 together the next can be 56
#So lets learn this sequence

x= train_data[:block_size] #18 is the fist 
y=train_data[1:block_size+1] # the target can be 47
for t in range(block_size):
    context = x[:t+1]
    target=y[t]
    print(f"When input is {context} the target is:{target}")

#these are the 8 characters


When input is tensor([18]) the target is:47
When input is tensor([18, 47]) the target is:56
When input is tensor([18, 47, 56]) the target is:57
When input is tensor([18, 47, 56, 57]) the target is:58
When input is tensor([18, 47, 56, 57, 58]) the target is:1
When input is tensor([18, 47, 56, 57, 58,  1]) the target is:15
When input is tensor([18, 47, 56, 57, 58,  1, 15]) the target is:47
When input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target is:58


In [ ]:
#Batch dimension: as we are sampling, it is best adavaced to work on multiple batches
#At a Time to keep the GPU BUSY
#We are working with different batches at once and train the transformer with multile batches of data in them there are chunck of different block sizes
# and they all work very independently


torch.manual_seed(1337) # we are setting the seed so that random_generation will be the same the next time
batch_size = 4 #how many batches are we processing in the both forward and backward pass in the tranformer
block_size= 8 #the max lendth


def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data)-block_size,(batch_size,)) #4 numbers that are randomly generated #ix would be 4 numbers that are randomly renerated
    x= torch.stack([data[i:i+8] for i in ix]) #X is the first block size character
    y = torch.stack([data[i+1:i+8+1] for i in ix]) #Target
    #x when ix generates a random number 2 	[2, 3, 4, 5, 6, 7, 8, 9]
    # y when x and ix consider 2 	[3, 4, 5, 6, 7, 8, 9, 10]
    return x,y

xb,yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets')
print(yb.shape)
print(yb)

print('---------------')

for b in range(batch_size): #this is the batch dimension
    for t in range(block_size): #this is the time dimension
        context = xb[b,:t+1]
        target=yb[b,t]
        print(f'when input is {context.tolist()} the target: {target}')


#these are the 32 examples 
#we are goint to process the independent varibale x to the transformer and the tranformer
#would simentously look for their answers in the targets


inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
---------------
when input is [24] the target: 43
when input is [24, 43] the target: 58
when input is [24, 43, 58] the target: 5
when input is [24, 43, 58, 5] the target: 57
when input is [24, 43, 58, 5, 57] the target: 1
when input is [24, 43, 58, 5, 57, 1] the target: 46
when input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when input is [44] the target: 53
when input is [44, 53] the target: 56
when input is [44, 53, 56] the target: 1
when input is [44, 53, 56, 1] the target: 58
when input is [44, 53, 56, 1, 58] the target: 46
when input 

In [24]:
print(xb)

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


In [35]:
# Implementing a Bigram Language Model
# This is the simplest model used for understanding the relationships between words.
# More complex models, such as Transformers, can capture more intricate patterns, 
# but the Bigram model is a good starting point.

import torch
import torch.nn as nn  # Import neural network module
from torch.nn import functional as F  # Import functional API for loss functions
torch.manual_seed(1337)  # Set random seed for reproducibility

class BigramLanguageModel(nn.Module):
    """
    Implementing the Bigram Language Model using a neural network model class.
    The Bigram model predicts the next token based on the current token.
    """

    def __init__(self, vocab_size):
        """
        Initializes the BigramLanguageModel.
        Arguments:
        vocab_size -- the number of unique tokens in the vocabulary.
        """
        super().__init__()
        # Each token directly retrieves the logits (probability distribution) for the next token from a lookup table.
        # This embedding table has a shape of (vocab_size, vocab_size),
        # meaning that each token has a unique vector representing the probability of transitioning to any other token.
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        """
        Defines the forward pass of the model.
        Arguments:
        idx -- a tensor of token indices, shape (B, T), where B is the batch size and T is the sequence length.
        targets -- the expected output tokens, shape (B, T), used for computing the loss.

        Returns:
        logits -- predicted next token probabilities (logits), shape (B, T, C), where C is the vocab_size.
        loss -- computed cross-entropy loss if targets are provided, otherwise None.
        """
        # Get the logits (raw predictions) from the embedding table.
        logits = self.token_embedding_table(idx)  # Shape: (B, T, C)

        # Initialize loss as None (it will only be computed if targets are provided)
        loss = None  
        if targets is not None:
            # Reshape logits and targets for computing loss
            B, T, C = logits.shape  # B = batch size, T = sequence length, C = vocab size
            logits = logits.view(B * T, C)  # Flatten logits to (B*T, C) to match targets
            targets = targets.view(B * T)  # Flatten targets to (B*T)

            # Compute the loss using Cross-Entropy, which measures the difference between predicted and actual values.
            loss = F.cross_entropy(logits, targets)

        return logits, loss  # Return the logits and the computed loss

    def generate(self, idx, max_new_tokens):
        """
        Generates a sequence of tokens based on the learned Bigram model.
        Arguments:
        idx -- (B, T) tensor containing initial token indices.
        max_new_tokens -- number of tokens to generate.

        Returns:
        idx -- (B, T + max_new_tokens) tensor with generated tokens.
        """
        for _ in range(max_new_tokens):
            # Get predictions for the current sequence
            logits, _ = self(idx)  # Shape: (B, T, C)

            # Focus only on the last time step (most recent token)
            logits = logits[:, -1, :]  # Shape: (B, C)

            # Apply softmax to convert logits into probabilities
            probs = F.softmax(logits, dim=-1)  # Shape: (B, C)

            # Sample the next token from the probability distribution
            idx_next = torch.multinomial(probs, num_samples=1)  # Shape: (B, 1)

            # Append the new token to the running sequence
            idx = torch.cat((idx, idx_next), dim=1)  # Concatenate along sequence dimension

        return idx


# Example usage:
# Define the vocabulary size (number of unique tokens in the dataset)
# vocab_size = 65  

# Generate some random input data for this example:
# xb = torch.randint(0, vocab_size, (4, 8))  # Simulate a batch of 4 sequences, each of length 8
# yb = torch.randint(0, vocab_size, (4, 8))  # Simulate the corresponding target tokens for each sequence

# Initialize the BigramLanguageModel with the vocab size
model = BigramLanguageModel(vocab_size)

# Forward pass to compute logits and loss
logits, loss = model(xb, yb)

print(logits.shape)  # Output shape of logits (B, T, C), showing predicted token probabilities
print(f"Loss: {loss.item()}")  # Print computed loss value

# Generate a sequence using the trained model
print(decode(model.generate(idx=torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

# Note: The initial loss is quite high (~4.87), which is expected in the first training round.
# A well-trained model typically achieves a loss between 2.5 and 3.5.


torch.Size([32, 65])
Loss: 4.878634929656982

Sr?qP-QWktXoL&jLDJgOLVz'RIoDqHdhsV&vLLxatjscMpwLERSPyao.qfzs$Ys$zF-w,;eEkzxjgCKFChs!iWW.ObzDnxA Ms$3


In [39]:
#rightnow we arent using an history
optimizer = torch.optim.AdamW(model.parameters(),lr=1e-3) #lr= learning rate

In [54]:
batch_size = 32
for steps in range(10000): # increase number of steps for good results...
    # sample a batch of data
    xb, yb = get_batch('train')
    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
print(loss.item())


2.3907620906829834


In [76]:
print(decode(model.generate(idx=torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))



'e LAgour melaird sheficowaglsesamazo ff denfacord haitonghit astees rsit.
NG sus
A:
I Wenore ponelers wan,
t y t whouem, rathe
D Poll f woors ulinomot oo, w abepusant IONESourceve; iourse menard, me Isf rowinkis; '
Wh kincld he trt murost, ETEY:

MNTove my lve y hal My o tr fly abe, ccouthem hampppu fes alo d, de datid a caie bupprken gatowhend,
IUTA:
Pins the ghasul Hithumeramey thithac! hearousifrme! hang herwiged opat aup?


WI besm?
Wher apld w y pe w d, dimist; thad aco e t,
I'daiod
'd sp


### the mathemical trick in self-attention

In [97]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [106]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape
x

tensor([[[ 0.1808, -0.0700],
         [-0.3596, -0.9152],
         [ 0.6258,  0.0255],
         [ 0.9545,  0.0643],
         [ 0.3612,  1.1679],
         [-1.3499, -0.5102],
         [ 0.2360, -0.2398],
         [-0.9211,  1.5433]],

        [[ 1.3488, -0.1396],
         [ 0.2858,  0.9651],
         [-2.0371,  0.4931],
         [ 1.4870,  0.5910],
         [ 0.1260, -1.5627],
         [-1.1601, -0.3348],
         [ 0.4478, -0.8016],
         [ 1.5236,  2.5086]],

        [[-0.6631, -0.2513],
         [ 1.0101,  0.1215],
         [ 0.1584,  1.1340],
         [-1.1539, -0.2984],
         [-0.5075, -0.9239],
         [ 0.5467, -1.4948],
         [-1.2057,  0.5718],
         [-0.5974, -0.6937]],

        [[ 1.6455, -0.8030],
         [ 1.3514, -0.2759],
         [-1.5108,  2.1048],
         [ 2.7630, -1.7465],
         [ 1.4516, -1.5103],
         [ 0.8212, -0.2115],
         [ 0.7789,  1.5333],
         [ 1.6097, -0.4032]]])

In [101]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [102]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T)) 
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [104]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [105]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)